export const ADD_SERVICE = 'ADD_SERVICE';
export const REMOVE_SERVICE = 'REMOVE_SERVICE';
export const CHANGE_SERVICE_FIELD = 'CHANGE_SERVICE_FIELD';
export const EDIT_SERVICE = 'EDIT_SERVICE';
export const FILL_SERVICE_FIELD = 'FILL_SERVICE_FIELD';
export const CLEAR_SERVICE_FIELD = 'CLEAR_SERVICE_FIELD';

export const ADD_PRODUCT = 'ADD_PRODUCT';
export const CHANGE_CATALOG_FORM = 'CHANGE_CATALOG_FORM';


